// Integration tests for `agent-cortex install copilot`: the install-time
// generator for the self-contained Copilot CLI plugin subtree (copilot/).
// All tests install into mkdtemp dirs so the real repo copilot/ is only ever
// read (the drift test compares generated bytes against the committed tree).

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, mkdir, writeFile, rm, readFile, readdir, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { join, dirname, relative } from "node:path";
import { installCopilot } from "../bin/installers/copilot.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const CLI_PATH = join(ROOT, "bin", "agent-cortex.mjs");

/** True when a path exists (stat succeeds). */
async function pathExists(p) {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

function runCli(args) {
  return new Promise((resolve) => {
    execFile(process.execPath, [CLI_PATH, ...args], (error, stdout, stderr) => {
      resolve({ exitCode: error ? error.code ?? 1 : 0, stdout, stderr });
    });
  });
}

// ─── Fixtures ────────────────────────────────────────────────────────────────

function tokenMap() {
  return {
    name: "fixture token map",
    version: 1,
    harnesses: ["copilot"],
    tools: {
      bash: { copilot: "bash" },
      view: { copilot: "view" },
      task: { copilot: "task" },
      ask_user: { copilot: "ask_user" },
      wait_for_agents: { copilot: null },
    },
    paths: {
      plugin_root: { copilot: "~/.copilot/installed-plugins/_direct/agent-cortex" },
      agents_dir: { copilot: { base: "plugin_root", relative: "agents" } },
      skills_dir: { copilot: { base: "plugin_root", relative: "skills" } },
    },
  };
}

/** Root Copilot manifest shape the subtree manifest is copied from. */
function rootPluginManifest() {
  return {
    name: "agent-cortex",
    description: "Personal Copilot CLI plugin with custom agents and skills",
    version: "0.0.0",
    author: { name: "jaybeeuu" },
    license: "MIT",
    repository: "https://github.com/jaybeeuu/agent-cortex",
    bin: "bin/agent-cortex.mjs",
    agents: "agents/",
    skills: "skills/",
    mcpServers: { context7: { type: "stdio", command: "npx", args: ["-y", "@upstash/context7-mcp@latest"] } },
    hooks: "hooks.json",
  };
}

async function makeFixture() {
  const root = await mkdtemp(join(tmpdir(), "copilot-installer-"));
  return {
    root,
    output: join(root, "plugin"),
    cleanup: async () => rm(root, { recursive: true, force: true }),
  };
}

async function writeFixture(fx, relPath, content) {
  const p = join(fx.root, relPath);
  await mkdir(dirname(p), { recursive: true });
  await writeFile(p, content);
}

/** Seed a minimal but realistic package tree (agents, skills, token-map, manifests). */
async function seedCopilotPackage(fx, opts = {}) {
  const { agents = {}, skills = {}, pluginVersion = "1.2.3" } = opts;
  await writeFixture(fx, "token-map.json", JSON.stringify(tokenMap()));
  await writeFixture(
    fx,
    "package.json",
    JSON.stringify({ name: "@jaybeeuu/agent-cortex", version: pluginVersion }),
  );
  await writeFixture(fx, "plugin.json", JSON.stringify(rootPluginManifest()));
  await writeFixture(fx, "hooks.json", JSON.stringify({ hooks: { sessionStart: [] } }));

  for (const [name, def] of Object.entries(agents)) {
    await writeFixture(fx, `agents/${name}/agent.md`, def.body ?? `# ${name}\nBody of ${name}.`);
    await writeFixture(
      fx,
      `agents/${name}/copilot/frontmatter.json`,
      JSON.stringify(
        def.frontmatter ?? {
          name: `agent-cortex:${name}`,
          description: `Description of ${name}`,
          tools: ["bash", "view"],
          argumentHint: `Hint for ${name}`,
        },
      ),
    );
    for (const [section, content] of Object.entries(def.sections ?? {})) {
      await writeFixture(fx, `agents/${name}/copilot/${section}.md`, content);
    }
  }

  for (const [skillPath, def] of Object.entries(skills)) {
    const files = def.files ?? { "SKILL.md": `# ${skillPath}\n` };
    for (const [rel, content] of Object.entries(files)) {
      await writeFixture(fx, `skills/${skillPath}/${rel}`, content);
    }
  }
}

/** Deterministic snapshot of a directory: relative paths + byte content. */
async function snapshot(dir, base = dir) {
  const entries = [];
  for (const e of (await readdir(dir, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
    const full = join(dir, e.name);
    const rel = relative(base, full);
    if (e.isDirectory()) {
      entries.push([rel, "dir"]);
      entries.push(...(await snapshot(full, base)));
    } else {
      entries.push([rel, "file", await readFile(full, "utf-8")]);
    }
  }
  return entries;
}

// ─── Plugin subtree ──────────────────────────────────────────────────────────

describe("installCopilot — plugin subtree", () => {
  it("builds the self-contained plugin subtree in <root>/copilot by default", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, {
        agents: { alpha: { body: "# alpha" } },
        skills: { "planning/alpha-skill": {} },
      });

      const result = await installCopilot({ root: fx.root });

      assert.equal(result.output, join(fx.root, "copilot"));
      assert.ok(await pathExists(join(fx.root, "copilot", "plugin.json")), "plugin manifest written");
      assert.ok(await pathExists(join(fx.root, "copilot", "agents", "alpha.agent.md")), "agent written under agents/");
      assert.ok(
        await pathExists(join(fx.root, "copilot", "skills", "planning", "alpha-skill", "SKILL.md")),
        "skill copied preserving its group dir",
      );
      assert.ok(await pathExists(join(fx.root, "copilot", "hooks.json")), "hooks.json copied for the manifest target");
      assert.equal(
        await pathExists(join(fx.root, "agents", "alpha.agent.md")),
        false,
        "no flat file scattered next to the composable source",
      );
      assert.deepEqual(result.agents, ["alpha"]);
      assert.deepEqual(result.skills.names, ["alpha-skill"]);
    } finally {
      await fx.cleanup();
    }
  });

  it("emits a plugin.json mirroring the root manifest with subtree paths, the package version, and no package-only bin", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, { agents: { alpha: { body: "# alpha" } }, pluginVersion: "9.9.9" });

      await installCopilot({ root: fx.root });

      const manifest = JSON.parse(await readFile(join(fx.root, "copilot", "plugin.json"), "utf-8"));
      assert.equal(manifest.name, "agent-cortex");
      assert.equal(manifest.description, "Personal Copilot CLI plugin with custom agents and skills");
      assert.equal(manifest.version, "9.9.9", "version tracks package.json");
      assert.equal(manifest.agents, "./agents");
      assert.equal(manifest.skills, "./skills");
      assert.equal(manifest.hooks, "hooks.json");
      assert.deepEqual(manifest.mcpServers, rootPluginManifest().mcpServers, "mcpServers copied verbatim");
      assert.equal("bin" in manifest, false, "package-only bin entry dropped");
    } finally {
      await fx.cleanup();
    }
  });

  it("removes stale generated children before regenerating", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, { agents: { alpha: { body: "# alpha" } } });
      await writeFixture(fx, "copilot/agents/stale.agent.md", "# stale\n");
      await writeFixture(fx, "copilot/plugin.json", "{}\n");

      await installCopilot({ root: fx.root });

      assert.equal(await pathExists(join(fx.root, "copilot", "agents", "stale.agent.md")), false, "stale agent removed");
      const manifest = JSON.parse(await readFile(join(fx.root, "copilot", "plugin.json"), "utf-8"));
      assert.equal(manifest.name, "agent-cortex", "manifest regenerated, not left stale");
    } finally {
      await fx.cleanup();
    }
  });
});

// ─── Skills ──────────────────────────────────────────────────────────────────

describe("installCopilot — skills", () => {
  it("substitutes copilot tokens in markdown, drops null-mapped tools with a warning, and copies other files verbatim", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, {
        skills: {
          "workflow/ralph-lite": {
            files: {
              "SKILL.md": "# ralph-lite\nRead with {{TOOL:view}}; PI waits with {{TOOL:wait_for_agents}}.\n",
              "asset.json": '{"token": "{{TOOL:view}}"}',
            },
          },
        },
      });

      const result = await installCopilot({ root: fx.root });

      const skill = await readFile(
        join(fx.root, "copilot", "skills", "workflow", "ralph-lite", "SKILL.md"),
        "utf-8",
      );
      assert.ok(skill.includes("Read with view;"), "{{TOOL:view}} substituted against the copilot column");
      assert.ok(!skill.includes("wait_for_agents"), "null-mapped tool dropped rather than left literal");
      assert.ok(!/\{\{/.test(skill), "no literal tokens remain");
      const asset = await readFile(
        join(fx.root, "copilot", "skills", "workflow", "ralph-lite", "asset.json"),
        "utf-8",
      );
      assert.equal(asset, '{"token": "{{TOOL:view}}"}', "non-markdown copied verbatim (never transformed)");
      assert.equal(result.warnings.length, 1);
      assert.match(result.warnings[0], /wait_for_agents/);
    } finally {
      await fx.cleanup();
    }
  });

  it("throws on an unknown tool token in a skill", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, { skills: { "planning/bad": { files: { "SKILL.md": "Use {{TOOL:nope}}." } } } });
      await assert.rejects(installCopilot({ root: fx.root }), /unknown tool token \{\{TOOL:nope\}\}/);
    } finally {
      await fx.cleanup();
    }
  });

  it("never copies local node_modules build artifacts into the subtree", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, {
        skills: { "planning/with-deps": { files: { "scripts/node_modules/dep/index.js": "module.exports = {};\n" } } },
      });

      await installCopilot({ root: fx.root });

      assert.equal(
        await pathExists(join(fx.root, "copilot", "skills", "planning", "with-deps", "scripts", "node_modules")),
        false,
      );
    } finally {
      await fx.cleanup();
    }
  });
});

// ─── Agent composition ───────────────────────────────────────────────────────

describe("installCopilot — agent composition", () => {
  it("writes one flat <name>.agent.md per composable agent dir with copilot frontmatter and no leftover tokens", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, {
        agents: {
          alpha: {
            body: "# alpha\nUse {{TOOL:view}} to read.\n{{SECTION:polling}}\nRead {{PATH:agents_dir}}.",
            sections: { polling: "Spawn with {{TOOL:task}}." },
            frontmatter: {
              name: "agent-cortex:alpha",
              description: "Reads things.",
              tools: ["bash", "view"],
              argumentHint: "Read something",
            },
          },
        },
      });

      const result = await installCopilot({ root: fx.root, output: fx.output });

      const file = join(fx.output, "agents", "alpha.agent.md");
      assert.ok(await pathExists(file), "flat agent file written under agents/");
      const content = await readFile(file, "utf-8");
      assert.ok(content.startsWith("---\n"), "yaml frontmatter");
      assert.ok(content.includes("# GENERATED from agents/alpha/ by scripts/build-copilot-agents.mjs — DO NOT EDIT."));
      // Committed flat-file field order: description, name, tools (YAML array), argument-hint.
      const order = ["description:", "name: \"agent-cortex:alpha\"", "tools: [", "argument-hint:"].map((s) => content.indexOf(s));
      assert.ok(order.every((i) => i !== -1), "all frontmatter fields present");
      assert.deepEqual([...order].sort((a, b) => a - b), order, "frontmatter fields in committed order");
      assert.match(content, /tools: \["bash", "view"\]/, "copilot tools kept as a YAML array (no translation)");
      assert.ok(content.includes("Use view to read."), "{{TOOL:view}} substituted");
      assert.ok(content.includes("Spawn with task."), "{{SECTION:polling}} composed from copilot/polling.md");
      assert.ok(content.includes("Read ~/.copilot/installed-plugins/_direct/agent-cortex/agents."), "{{PATH:agents_dir}} resolved");
      assert.ok(!/{{/.test(content), "no literal tokens remain");
      assert.deepEqual(result.agents, ["alpha"]);
    } finally {
      await fx.cleanup();
    }
  });

  it("skips non-composable entries in agents/ and never clobbers composable sources", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, { agents: { alpha: { body: "# alpha" } } });
      await writeFixture(fx, "agents/README.md", "# agents dir docs\n");

      const result = await installCopilot({ root: fx.root, output: fx.output });

      assert.deepEqual((await readdir(join(fx.output, "agents"))).sort(), ["alpha.agent.md"], "no README, no subdirectories");
      assert.deepEqual(result.agents, ["alpha"]);
      assert.ok(await pathExists(join(fx.root, "agents", "alpha", "agent.md")), "composable source preserved");
      assert.ok(await pathExists(join(fx.root, "agents", "alpha", "copilot", "frontmatter.json")), "harness dir preserved");
    } finally {
      await fx.cleanup();
    }
  });

  it("throws when a composable dir lacks copilot/frontmatter.json", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, { agents: { alpha: { body: "# alpha" } } });
      await rm(join(fx.root, "agents", "alpha", "copilot"), { recursive: true, force: true });
      await assert.rejects(
        installCopilot({ root: fx.root, output: fx.output }),
        /without copilot\/frontmatter\.json/,
      );
    } finally {
      await fx.cleanup();
    }
  });

  it("throws on an unknown tool token", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, { agents: { alpha: { body: "# alpha\nUse {{TOOL:nope}} now." } } });
      await assert.rejects(installCopilot({ root: fx.root, output: fx.output }), /unknown tool token \{\{TOOL:nope\}\}/);
    } finally {
      await fx.cleanup();
    }
  });
});

// ─── Output / dry-run ────────────────────────────────────────────────────────

describe("installCopilot — output & dry-run", () => {
  it("dry-run reports the plan without writing anything", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, { agents: { alpha: { body: "# alpha" } }, skills: { "planning/alpha-skill": {} } });

      const result = await installCopilot({ root: fx.root, dryRun: true });

      assert.equal(result.dryRun, true);
      assert.equal(await pathExists(join(fx.root, "copilot")), false, "no output dir created in dry-run");
      assert.deepEqual(result.agents, ["alpha"], "planned agents still reported");
      assert.deepEqual(result.skills.names, ["alpha-skill"], "planned skills still reported");
      assert.equal(result.pluginVersion, "1.2.3", "planned manifest version still reported");
    } finally {
      await fx.cleanup();
    }
  });

  it("is deterministic across repeated installs into the same output", async () => {
    const fx = await makeFixture();
    try {
      await seedCopilotPackage(fx, {
        agents: {
          alpha: { body: "# alpha\n{{SECTION:polling}}", sections: { polling: "Poll with {{TOOL:task}}." } },
          beta: { body: "# beta" },
        },
        skills: { "workflow/beta-skill": { files: { "SKILL.md": "Use {{TOOL:bash}}." } } },
      });

      await installCopilot({ root: fx.root, output: fx.output });
      const first = await snapshot(fx.output);
      await installCopilot({ root: fx.root, output: fx.output });
      assert.deepEqual(await snapshot(fx.output), first);
    } finally {
      await fx.cleanup();
    }
  });
});

// ─── Integration against the real repo ───────────────────────────────────────

describe("installCopilot — real repo integration", () => {
  it("regenerates a byte-identical copy of the committed copilot/ subtree (CI drift check)", async () => {
    const fx = await makeFixture();
    try {
      const committed = join(ROOT, "copilot");
      assert.ok(await pathExists(committed), "copilot/ subtree is committed");

      await installCopilot({ root: ROOT, output: fx.output });

      assert.deepEqual(await snapshot(fx.output), await snapshot(committed));
    } finally {
      await fx.cleanup();
    }
  });
});

// ─── CLI wiring ──────────────────────────────────────────────────────────────

describe("CLI integration", () => {
  it("exits 0 for install copilot --output <tmp> and writes the plugin subtree", async () => {
    const fx = await makeFixture();
    try {
      const { exitCode, stdout } = await runCli(["install", "copilot", "--output", fx.output]);
      assert.equal(exitCode, 0);
      assert.ok(stdout.includes("copilot"), "prints the target path");
      assert.ok(await pathExists(join(fx.output, "plugin.json")), "manifest written");
      assert.ok(await pathExists(join(fx.output, "agents", "ralph.agent.md")), "agent files written");
      assert.ok(await pathExists(join(fx.output, "skills", "engineering", "tdd", "SKILL.md")), "skills copied");
      assert.ok(await pathExists(join(fx.output, "hooks.json")), "hooks copied");
    } finally {
      await fx.cleanup();
    }
  });

  it("exits 0 for install copilot --dry-run and writes nothing", async () => {
    const fx = await makeFixture();
    try {
      const { exitCode, stdout } = await runCli(["install", "copilot", "--output", fx.output, "--dry-run"]);
      assert.equal(exitCode, 0);
      assert.ok(/dry-run/i.test(stdout));
      assert.equal(await pathExists(fx.output), false, "no files written in dry-run");
    } finally {
      await fx.cleanup();
    }
  });

  it("exits 0 for install copilot (default output) without touching committed files", async () => {
    const before = await snapshot(join(ROOT, "copilot"));
    const { exitCode } = await runCli(["install", "copilot"]);
    assert.equal(exitCode, 0);
    // Default output regenerates the committed copilot/ subtree in place —
    // output must stay byte-identical to what is committed.
    assert.deepEqual(await snapshot(join(ROOT, "copilot")), before);
  });
});
